app/content/urls.py
from django.urls import path

from . import views

app_name = "content"

urlpatterns = [
    path("", view=views.Index.as_view(), name="index"),
    path("video", view=views.VideoList.as_view(), name="video-list"),
    path("video/<int:pk>", view=views.VideoDetail.as_view(), name="video-detail"),
    path("video/<int:pk>/edit", view=views.VideoEdit.as_view(), name="video-edit"),
    path("genre", view=views.GenreList.as_view(), name="genre-list"),
    path("actor", view=views.ActorList.as_view(), name="actor-list"),
    path("staff", view=views.StaffList.as_view(), name="staff-list"),
]

config/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include

from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("login/", LoginView.as_view(template_name="auth/login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("", views.index, name="index"),
    path("api/", include('app.api.urls'), name='api'),
    path("builder/", include('app.builder.urls'), name='builder'),
    path("content/", include('app.content.urls'), name='content'),
    path("dashboard/", include('app.dashboard.urls'), name='dashboard'),
]

app/content/models.py
from django.db import models

# Create your models here.

app/content/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Count
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import TemplateView, ListView, DetailView

from app.database.models import Video, Genre, Actor, Staff, CountryCode
from app.database.queryset import video as queryset
from app.utils.uploader import S3ImageUploader
from app.utils.utils import make_s3_path
from config.constraints import (
    VIDEO_CODE,
    VIDEO_PLATFORM_CODE,
    VIDEO_THUMBNAIL_CODE,
    VIDEO_ACTOR_CODE,
    VIDEO_STAFF_CODE
)
from config.settings.settings import AWS_S3_BASE_URL

DJANGO_LOGIN_URL = "/login/"
DJANGO_REDIRECT_FIELD_NAME = "next"


# Create your views here.
class Index(LoginRequiredMixin, TemplateView):
    login_url = DJANGO_LOGIN_URL
    redirect_field_name = DJANGO_REDIRECT_FIELD_NAME
    template_name = "pages/content/index.html"


class VideoList(LoginRequiredMixin, ListView):
    paginate_by = 20
    login_url = DJANGO_LOGIN_URL
    redirect_field_name = DJANGO_REDIRECT_FIELD_NAME
    model = Video
    template_name = "pages/content/video/list.html"
    context_object_name = "videos"

    def get_queryset(self):
        query_set = super().get_queryset().order_by('id')
        keyword = self.request.GET.get('q', '')
        gid = self.request.GET.get('gid', '')
        aid = self.request.GET.get('aid', '')
        sid = self.request.GET.get('sid', '')
        is_confirm = self.request.GET.get('cfm', '')
        is_delete = self.request.GET.get('del', '')
        if keyword:
            query_set = query_set.filter(title__icontains=keyword)
        if gid:
            query_set = query_set.filter(genre_list__genre_id=gid)
        if aid:
            query_set = query_set.filter(actor_list__actor_id=aid)
        if sid:
            query_set = query_set.filter(staff_list__staff_id=sid)
        if is_confirm != "" and is_confirm in ["true", "false"]:
            query_set = query_set.filter(is_confirm=(is_confirm == 'true'))
        if is_delete != "" and is_delete in ["true", "false"]:
            query_set = query_set.filter(is_delete=(is_delete == 'true'))
        return query_set

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['q'] = self.request.GET.get('q', '')
        context['cfm'] = self.request.GET.get('cfm', '')
        context['del'] = self.request.GET.get('del', '')
        videos = VideoList.set_thumbnail_urls_and_orientation(context['videos'])
        context['videos'] = videos

        # 페이지네이션 컨텍스트 추가
        paginator = context['paginator']
        page_obj = context['page_obj']
        is_paginated = context['is_paginated']
        context['paginator'] = paginator
        context['page_obj'] = page_obj
        context['is_paginated'] = is_paginated

        return context

    @classmethod
    def set_thumbnail_urls_and_orientation(cls, videos):
        for video in videos:
            video.is_mainimage = False
            for thumbnail in video.thumbnail.all():
                thumbnail.url = AWS_S3_BASE_URL + thumbnail.url
                if thumbnail.code == "10":
                    video.is_mainimage = True
        return videos


class VideoDetail(LoginRequiredMixin, DetailView):
    login_url = DJANGO_LOGIN_URL
    redirect_field_name = DJANGO_REDIRECT_FIELD_NAME
    model = Video
    template_name = "pages/content/video/detail.html"


class VideoEdit(LoginRequiredMixin, DetailView):
    login_url = DJANGO_LOGIN_URL
    redirect_field_name = DJANGO_REDIRECT_FIELD_NAME
    model = Video
    template_name = "pages/content/video/edit.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        video = self.get_object()
        context['video_code'] = VIDEO_CODE
        context['video_platform_code'] = VIDEO_PLATFORM_CODE
        context['video_actor_code'] = VIDEO_ACTOR_CODE
        context['video_staff_code'] = VIDEO_STAFF_CODE
        context['video_thumbnail_code'] = VIDEO_THUMBNAIL_CODE
        context['video_platform_code'] = VIDEO_PLATFORM_CODE
        context['video_genre_list'] = video.genre_list.all().order_by('sort', 'id')
        context['video_actor_list'] = video.actor_list.all().order_by('sort', 'code')
        context['video_staff_list'] = video.staff_list.all().order_by('sort', 'code')
        context['video_thumbnail_list'] = video.thumbnail.all().order_by('code', 'sort')
        context['video_platform_list'] = video.platform.all().order_by('code')
        context['country_code_list'] = CountryCode.objects.all()
        return context

    def post(self, request, *args, **kwargs):
        edit_type = request.POST.get('edit_type')
        video_id = kwargs.get('pk')
        video = Video.objects.get(id=video_id)
        # 비디오 정보가 없으면 리턴
        if not video:
            print('video not found')
            return render(request, self.template_name)
        # 기본정보 수정
        if edit_type == "basic":
            # 비디오 제목
            title = request.POST.get('title')
            # 비디오 타입
            video_code = request.POST.get('code')
            # 개봉일
            release = request.POST.get('release')
            # 런타임
            runtime = request.POST.get('runtime')
            # 연령 고지
            notice_age = request.POST.get('notice_age')
            # 제작사
            # production = request.POST.get('production')
            # 제작국가
            country = request.POST.get('country')
            # 시놉시스
            synopsis = request.POST.get('synopsis')
            # 관리자 확인
            is_confirm = request.POST.get('is_confirm') == "true"
            queryset.update_video(video, {
                'title': title,
                'code': video_code,
                'release': release,
                'runtime': runtime,
                'notice_age': notice_age,
                'country': country,
                'synopsis': synopsis,
                'is_confirm': is_confirm
            })
            # 비디오 상세 페이지로 리다이렉트
            return HttpResponseRedirect(reverse('content:video-detail', kwargs={'pk': video_id}))
        # 썸네일 생성/수정/삭제
        elif edit_type == "thumbnail":
            thumbnail_create = request.POST.get('thumbnail_create')
            thumbnail_delete = request.POST.get('thumbnail_delete')
            # 썸네일 생성 요청 확인
            if thumbnail_create:
                # 생성요청 썸네일 리스트
                thumbnail_create_list = thumbnail_create.split(',')
                # S3 이미지업로더 생성
                uploader = S3ImageUploader()
                # 생성요청 썸네일 리스트 Loop
                for thumbnail_id in thumbnail_create_list:
                    # 썸네일 정보 가져오기
                    code = request.POST.get('thumbnail_code_' + thumbnail_id)
                    url = request.POST.get('thumbnail_url_' + thumbnail_id)
                    sort = request.POST.get('thumbnail_sort_' + thumbnail_id)
                    upload_type = request.POST.get('thumbnail_upload_type_' + thumbnail_id)
                    # 썸네일 정보가 없으면 다음 썸네일로 이동
                    if not code or not url or not upload_type:
                        continue
                    try:
                        if upload_type == "url":
                            s3_path = make_s3_path("video", video.id, url)
                            result = uploader.upload_from_url(url, s3_path)
                        elif upload_type == "file":
                            file = request.FILES.get('thumbnail_file_' + thumbnail_id)
                            s3_path = make_s3_path("video", video.id, file.name)
                            result = uploader.upload_from_file(file, s3_path)
                        else:
                            raise Exception("Invalid upload type")
                        if not result:
                            raise Exception("Failed to upload the thumbnail")
                        # S3 업로드 성공 시 DB에 썸네일 정보 저장
                        queryset.create_video_thumbnail(video, {
                            'code': code,
                            'url': result['url'],
                            'extension': result['extension'],
                            'size': result['size'],
                            'width': result['width'],
                            'height': result['height'],
                            'sort': sort
                        })
                    except Exception as e:
                        print(e)
                # S3 이미지업로더 종료
                uploader.close()
            # 썸네일 삭제 요청 확인
            if thumbnail_delete:
                # 생성요청 썸네일 리스트
                thumbnail_delete_list = thumbnail_delete.split(',')
                for thumbnail_id in thumbnail_delete_list:
                    # 썸네일 삭제
                    queryset.delete_video_thumbnail(video, thumbnail_id)
            # 썸네일 수정
            for thumbnail in video.thumbnail.all():
                try:
                    # 입력된 썸네일 정보 가져오기
                    code = request.POST.get('thumbnail_code_' + str(thumbnail.id))
                    sort = request.POST.get('thumbnail_sort_' + str(thumbnail.id))
                    if not sort:
                        sort = 99
                    queryset.update_video_thumbnail(thumbnail, {
                        'code': code,
                        'sort': sort
                    })
                except Exception as e:
                    print(e)
            # 비디오 상세 페이지로 리다이렉트
            return HttpResponseRedirect(reverse('content:video-detail', kwargs={'pk': video_id}))
        # 시청 정보 생성/수정/삭제
        elif edit_type == "platform":
            platform_create = request.POST.get('platform_create')
            platform_delete = request.POST.get('platform_delete')
            # 시청정보 생성 요청 확인
            if platform_create:
                # 생성요청 시청정보 리스트
                platform_create_list = platform_create.split(',')

templates/pages/content/video/detail.html
{% extends 'layouts/main.html' %}
{% load static %}

{% block title %}넷플릭스{% endblock title %}

{% block content %}

<div class="flex flex-col gap-5 min-h-[calc(100vh-188px)] sm:min-h-[calc(100vh-204px)]">
    <h2 class="text-base font-semibold mb-4">비디오 관리</h2>

    {% if object %}

    <h1>{{object.title}}</h1>

    <a href="{% url 'content:video-edit' object.id %}">
        <button type="button" class="btn bg-dark dark:bg-white dark:text-dark dark:border-white border border-dark rounded-md text-white transition-all duration-300 hover:bg-dark/[0.85] hover:border-dark/[0.85]">수정</button>
    </a>

    {% endif %}

</div>

{% endblock content %}

templates/pages/content/video/list.html
{% extends 'layouts/main.html' %}
{% load static %}
{% load tags %}

{% block title %} 비디오 관리 {% endblock title %}

{% block menu-title %} 비디오 관리 {% endblock menu-title %}

{% block head %}
    <script src="{% static 'js/builder/collect/base.js' %}" defer></script>
    <link rel="stylesheet" href="{% static 'css/swiper-bundle.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
{% endblock head %}

{% block content %}

<div class="flex flex-col gap-5 min-h-[calc(100vh-188px)] sm:min-h-[calc(100vh-204px)]">
    <h2 class="text-base font-semibold mb-4">비디오 목록</h2>

    <div class="flex justify-between items-center gap-1.5">
        <form method="get" class="flex gap-1.5">
            <div class="flex justify-start items-center gap-1.5">
                <div class="relative">
                    <input
                        type="text"
                        name="q"
                        class="form-input ps-10 w-[280px] h-[42px] dark:border-lightgray/20 dark:text-white dark:bg-lightgray/10 border border-gray/10 bg-gray/[8%] rounded-[10px] text-sm text-dark placeholder:text-lightgray/80 focus:ring-0 focus:border-primary/80 focus:outline-0"
                        value="{{ q }}"
                        placeholder="타이틀 검색.."
                    >
                    <span class="absolute inset-y-0 left-3 flex items-center">
                        <svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <g clip-path="url(#clip0_87_857)">
                                <circle cx="8.625" cy="8.625" r="7.125" stroke="#267DFF" stroke-width="2" />
                                <path opacity="0.3" d="M15 15L16.5 16.5" stroke="#267DFF" stroke-width="2" stroke-linecap="round" />
                            </g>
                            <defs>
                                <clipPath id="clip0_87_857">
                                    <rect width="18" height="18" fill="white" />
                                </clipPath>
                            </defs>
                        </svg>
                    </span>
                </div>
                <select name="cfm" class="form-select h-10 px-5 rounded-[10px] hover:bg-gray/10 border border-gray/10 transition-all duration-300 font-semibold text-xs">
                    <option value="">전체</option>
                    {% if cfm == "true" %}
                        <option value="true" selected>관리자 승인</option>
                    {% else %}
                        <option value="true">관리자 승인</option>
                    {% endif %}
                    {% if cfm == "false" %}
                        <option value="false" selected>관리자 미승인</option>
                    {% else %}
                        <option value="false">관리자 미승인</option>
                    {% endif %}
                </select>
                <select name="del" class="form-select h-10 px-5 rounded-[10px] hover:bg-gray/10 border border-gray/10 transition-all duration-300 font-semibold text-xs">
                    <option value="">전체</option>
                    {% if del == "true" %}
                        <option value="true" selected>컨텐츠 삭제</option>
                    {% else %}
                        <option value="true">컨텐츠 삭제</option>
                    {% endif %}
                    {% if del == "false" %}
                        <option value="false" selected>컨텐츠 미삭제</option>
                    {% else %}
                        <option value="false">컨텐츠 미삭제</option>
                    {% endif %}
                </select>
            </div>
            <div class="flex justify-start items-center gap-1.5">
                <button type="submit" class="btn w-[100px] bg-primary text-white hover:bg-primary/[0.85] border border-gray/10 rounded-[10px] transition-all duration-300">검색</button>
            </div>
        </form>
        <div class="flex items-center gap-1.5">
            <button type="button" class="btn w-[100px] hover:bg-gray/10 border border-gray/10 rounded-[10px] transition-all duration-300">전체선택</button>
            <button type="button" class="btn w-[100px] hover:bg-gray/10 border border-gray/10 rounded-[10px] transition-all duration-300">선택승인</button>
            <button type="button" class="btn w-[100px] hover:bg-gray/10 border border-gray/10 rounded-[10px] transition-all duration-300">선택삭제</button>
        </div>
    </div>

    {% if videos.count > 0 %}
        <form action="" method="post" class="flex flex-col gap-1.5">
        {% for video in videos %}
            <div class="flex gap-1.5 bg-white dark:bg-dark dark:border-gray/20 border border-lightgray/10 p-5 rounded-lg">

                <div class="flex justify-start items-center w-[80px]">
                    <input type="checkbox" id="checkbox{{ video.id }}" class="form-checkbox h-5 w-5 text-primary" />
                    <label for="checkbox{{ video.id }}" class="ml-2 text-sm text-gray">{{ video.id }}</label>
                </div>

                <div class="w-[200px] h-auto overflow-hidden">
                    <div class="swiper SwiperwithPagination">
                        <div class="swiper-wrapper">
                            {%  for thumbnail in video.thumbnail.all %}
                                <div class="swiper-slide">
                                    <img src="{{ thumbnail.url|add_base_url }}" alt="slider" class="max-h-96 object-cover rounded-[10px]" style="width: 100%; height: 100%; object-fit: cover; object-position: center;"/>
                                </div>
                            {% endfor %}
                        </div>
                        <div class="swiper-pagination"></div>
                    </div>
                </div>

                <a href="{% url 'content:video-detail' video.id %}">
                    <div class="flex items-center gap-2.5">
                        <button type="button" class="btn w-[100px] hover:bg-gray/10 border border-gray/10 rounded-full transition-all duration-300">제목</button>
                        <div class="flex gap-1.5 px-1 text-gray">
                            {{ video.title }}
                            {% if not video.is_mainimage %} <span class="bg-danger/10 text-danger flex items-center gap-1 rounded-full py-1 px-2.5 text-xs">대표 이미지 없음</span> {% endif %}
                            {% if not video.is_confirm %} <span class="bg-success/10 text-success flex items-center gap-1 rounded-full py-1 px-2.5 text-xs">관리자 승인 필요</span> {% endif %}
                        </div>
                    </div>
                    <div class="flex items-center gap-2.5 mt-1">
                        <button type="button" class="btn w-[100px] hover:bg-gray/10 border border-gray/10 rounded-full transition-all duration-300">출시일</button>
                        <div class="w-[120px] px-1 text-gray">{{ video.release }}</div>
                        <button type="button" class="btn w-[100px] hover:bg-gray/10 border border-gray/10 rounded-full transition-all duration-300">상영시간</button>
                        <div class="w-[120px] px-1 text-gray">{{ video.runtime }}</div>
                        <button type="button" class="btn w-[100px] hover:bg-gray/10 border border-gray/10 rounded-full transition-all duration-300">관람등급</button>
                        <div class="w-[120px] px-1 text-gray">{{ video.notice_age }}</div>
                    </div>
                    <div class="flex flex-wrap items-center gap-2.5 mt-1 max-w-[1200px]">
                        <button type="button" class="btn w-[100px] hover:bg-gray/10 border border-gray/10 rounded-full transition-all duration-300">장르</button>
                        {% for genre in video.genre.all %}
                            <div class="flex items-center space-x-2.5 text-gray hover:text-dark dark:hover:text-white duration-300">
                                <span>{{ genre.name }}</span>
                                {% if not forloop.last %}
                                    <span class="text-xs">/</span>
                                {% endif %}
                            </div>
                        {% endfor %}
                    </div>
                    <div class="flex flex-wrap items-center gap-2.5 mt-1 max-w-[1200px]">
                        <button type="button" class="btn w-[100px] hover:bg-gray/10 border border-gray/10 rounded-full transition-all duration-300">출연</button>
                        {% for actor in video.actor.all %}
                            <div class="flex items-center flex-wrap overflow-hidden max-h-96 space-x-2.5 text-gray hover:text-dark dark:hover:text-white duration-300">
                                <span>{{ actor.name }}</span>
                                {% if not forloop.last %}
                                    <span class="text-xs">/</span>
                                {% endif %}
                            </div>
                        {% endfor %}
                    </div>
                    <div class="flex flex-wrap items-center gap-2.5 mt-1 max-w-[1200px]">
                        <button type="button" class="btn w-[100px] hover:bg-gray/10 border border-gray/10 rounded-full transition-all duration-300">제작</button>
                        {% for staff in video.staff.all %}
                            <div class="flex items-center space-x-2.5 text-gray hover:text-dark dark:hover:text-white duration-300">
                                <span>{{ staff.name }}</span>
                                {% if not forloop.last %}
                                    <span class="text-xs">/</span>
                                {% endif %}
                            </div>
                        {% endfor %}
                    </div>
                    <div class="flex items-center gap-2.5 mt-1 max-w-[1200px]">
                        <button type="button" class="btn w-[100px] hover:bg-gray/10 border border-gray/10 rounded-full transition-all duration-300">시놉시스</button>
                        <div class="text-gray">{{ video.synopsis|truncatechars:100 }}</div>
                    </div>
                </a>
            </div>
        {% endfor %}
        </form>
    {% else %}
        <div class="flex items-center justify-center w-full h-full py-10 text-gray/50 dark:text-gray/60">
            등록된 비디오가 없습니다.
        </div>
    {% endif %}

    {% if is_paginated %}
        <div class="pagination">
            <div class="overflow-scroll">
                <ul class="flex items-center gap-1 justify-center">
                    {% if page_obj.has_previous %}
                    <li>
                        <a href="?page={{ page_obj.previous_page_number }}&q={{ q|default:'' }}&cfm={{ cfm|default:'' }}&del={{ del|default:'' }}" class="bg-gray/20 hover:bg-primary hover:text-white duration-300 flex items-center justify-center hover:bg-dark/10 w-7 h-7 rounded-md">
                            <svg width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path d="M7.29289 10.7071C7.68342 11.0976 8.31658 11.0976 8.70711 10.7071C9.09763 10.3166 9.09763 9.68342 8.70711 9.29289L5.41421 6L8.70711 2.70711C9.09763 2.31658 9.09763 1.68342 8.70711 1.29289C8.31658 0.902369 7.68342 0.902369 7.29289 1.29289L3.29289 5.29289C2.90237 5.68342 2.90237 6.31658 3.29289 6.70711L7.29289 10.7071Z" fill="currentColor"></path>
                            </svg>
                        </a>
                    </li>
                    {% endif %}

                    {% for num in paginator.page_range %}
                        {% if num > page_obj.number|add:-5 and num < page_obj.number|add:5 %}
                            {% if num == page_obj.number %}
                                <a href="javascript:;" class="bg-gray/20 hover:bg-primary hover:text-white flex items-center justify-center bg-primary text-white w-7 h-7 rounded-md duration-300">{{ num }}</a>
                            {% else %}
                                <a href="?page={{ num }}&q={{ q|default:'' }}&cfm={{ cfm|default:'' }}&del={{ del|default:'' }}" class="bg-gray/20 hover:bg-primary hover:text-white flex items-center justify-center hover:bg-dark/10 w-7 h-7 rounded-md duration-300">{{ num }}</a>
                            {% endif %}
                        {% endif %}
                    {% endfor %}

                    {% if page_obj.has_next %}
                        <li>
                            <a href="?page={{ page_obj.next_page_number }}&q={{ q|default:'' }}&cfm={{ cfm|default:'' }}&del={{ del|default:'' }}" class="bg-gray/20 hover:bg-primary hover:text-white flex items-center justify-center hover:bg-dark/10 w-7 h-7 rounded-md duration-300">
                                <svg width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M4.70711 1.29289C4.31658 0.902369 3.68342 0.902369 3.29289 1.29289C2.90237 1.68342 2.90237 2.31658 3.29289 2.70711L6.58579 6L3.29289 9.29289C2.90237 9.68342 2.90237 10.3166 3.29289 10.7071C3.68342 11.0976 4.31658 11.0976 4.70711 10.7071L8.70711 6.70711C9.09763 6.31658 9.09763 5.68342 8.70711 5.29289L4.70711 1.29289Z" fill="currentColor"></path>
                                </svg>
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    {% endif %}

</div>

 <!-- Swiper Slider Js -->
 <script src="/static/js/swiper-bundle.min.js"></script>
 <script>
    const swiper = new Swiper(".SwiperwithPagination", {
        pagination: {
            el: ".swiper-pagination",
        },
    });
</script>

{% endblock content %}